version: '3.5'

services:

  fluentd:
    image: fluent/fluentd:v1.15-1
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  db:
    image: postgres
    restart: always
    env_file:
      - .env_dev
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/data
      - ./init-kts-db.sh:/docker-entrypoint-initdb.d/init-kts-db.sh
    networks:
      - kts_st_week3
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"


  adminer:
    image: adminer
    restart: always
    ports:
      - '6080:8080'
    networks:
      - kts_st_week3

  builder:
    env_file:
      - .env_dev
    build:
      context: .
      dockerfile: ./compose/builder.Dockerfile
    volumes:
      - .:/app
    networks:
      - kts_st_week3


  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    restart: always
    env_file:
      - .env_dev
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - kts_st_week3
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"


  poller_app:
    build:
      context: .
      dockerfile: ./compose/poller/Dockerfile
    image: feraclin/tg_bot_words:poller
    restart: always
    env_file:
      - .env_dev
    command: bash -c "cd /code/app/poller_app/ && python main.py"
    depends_on:
      - builder
      - db
      - rabbitmq
      - fluentd
    networks:
      - kts_st_week3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

  worker_app:
    build:
      context: .
      dockerfile: ./compose/worker/Dockerfile
    image: feraclin/tg_bot_words:worker
    restart: always
    env_file:
      - .env_dev
    command: bash -c "cd /code/app/worker_app/ && python main.py"
    depends_on:
      - poller_app
    networks:
      - kts_st_week3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

  sender_app:
    build:
      context: .
      dockerfile: ./compose/sender/Dockerfile
    image: feraclin/tg_bot_words:sender
    restart: always
    env_file:
      - .env_dev
    command: bash -c "cd /code/app/sender_app/ && python main.py"
    depends_on:
      - worker_app
    networks:
      - kts_st_week3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

  aiohttp_app:
    build:
      context: .
      dockerfile: ./compose/aiohttp_web/Dockerfile
    image: feraclin/tg_bot_words:aiohttp
    restart: always
    env_file:
      - .env_dev
    command: bash -c "alembic upgrade head && python aiohttp_app_main.py"
    depends_on:
      - builder
      - db
      - rabbitmq
      - fluentd
    ports:
      - "8080:8080"
    networks:
      - kts_st_week3
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"

volumes:
  pgdata:

networks:
  kts_st_week3:
    driver: bridge
