"""replace str to list[str] in gamesession

Revision ID: 120b334a60ea
Revises: 732604326100
Create Date: 2023-02-27 21:52:40.173372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120b334a60ea'
down_revision = '732604326100'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'words',
                    existing_type=sa.VARCHAR(),
                    type_=sa.ARRAY(sa.VARCHAR()),
                    postgresql_using='words::character varying[]',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'words',
                    existing_type=sa.ARRAY(sa.VARCHAR()),
                    type_=sa.VARCHAR(),
                    postgresql_using='words::character varying[]',
                    existing_nullable=False)
    # ### end Alembic commands ###
