"""GameSession add chat id and type

Revision ID: 1f9342abec42
Revises: f9989935b482
Create Date: 2023-02-23 16:14:59.122536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9342abec42'
down_revision = 'f9989935b482'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('game_type', sa.String(), nullable=False))
    op.add_column('game_sessions', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('words', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'words')
    op.drop_column('game_sessions', 'chat_id')
    op.drop_column('game_sessions', 'game_type')
    # ### end Alembic commands ###
