"""add used city MTM and first_letter and next player in GameSession

Revision ID: 52c6200e6487
Revises: 281f779aaf59
Create Date: 2023-02-23 08:15:51.549916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c6200e6487'
down_revision = '281f779aaf59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_sessions', sa.Column('next_user_id', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('next_start_letter', sa.String(), nullable=True))
    op.alter_column('game_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'game_sessions', 'users', ['next_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_sessions', 'users', ['winner_id'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('life', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'life')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.alter_column('game_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('game_sessions', 'next_start_letter')
    op.drop_column('game_sessions', 'winner_id')
    op.drop_column('game_sessions', 'next_user_id')
    op.drop_table('used_cities')
    # ### end Alembic commands ###
