"""city_country_region

Revision ID: 554e4954eedd
Revises: 0eb1c9274ed1
Create Date: 2023-02-22 22:45:02.678857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554e4954eedd'
down_revision = '0eb1c9274ed1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
