"""add_settings_to_session

Revision ID: 6f03b8ff38a4
Revises: ce90867f5d16
Create Date: 2023-03-17 16:10:10.018422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f03b8ff38a4'
down_revision = 'ce90867f5d16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('response_time', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('anonymous_poll', sa.Boolean(), nullable=False))
    op.add_column('game_sessions', sa.Column('poll_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'poll_time')
    op.drop_column('game_sessions', 'anonymous_poll')
    op.drop_column('game_sessions', 'response_time')
    # ### end Alembic commands ###
