"""rename user to creator

Revision ID: 9e5c6abfb6c4
Revises: 680d80f5e477
Create Date: 2023-03-03 10:07:17.516821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5c6abfb6c4'
down_revision = '680d80f5e477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='game_sessions',
                    column_name='user_id',
                    new_column_name='creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='game_sessions',
                    column_name='creator_id',
                    new_column_name='user_id')
    # ### end Alembic commands ###
