"""add poll_id to game session

Revision ID: bd75d43a5e03
Revises: 120b334a60ea
Create Date: 2023-02-28 11:56:25.008239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd75d43a5e03'
down_revision = '120b334a60ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('current_poll_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'current_poll_id')
    # ### end Alembic commands ###
