"""add_poll_answer_to_player

Revision ID: ce90867f5d16
Revises: 1fe91cbdaf6b
Create Date: 2023-03-16 22:56:40.114798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce90867f5d16'
down_revision = '1fe91cbdaf6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_sessions', sa.Column('poll_answer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_sessions', 'poll_answer')
    # ### end Alembic commands ###
