"""add_life_to_settings

Revision ID: e58e24333578
Revises: 6f03b8ff38a4
Create Date: 2023-03-17 16:48:44.705832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58e24333578'
down_revision = '6f03b8ff38a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('life', sa.Integer(), nullable=False))
    op.add_column('game_settings', sa.Column('life', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_settings', 'life')
    op.drop_column('game_sessions', 'life')
    # ### end Alembic commands ###
