user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzMyOTQ=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5434
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: group_token
  group_id: 1
rabbitmq:
  host: localhost
  port: 5673
  user: admin
  password: password

