name: Deploy to vps
on: [workflow_dispatch]
jobs:

    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v1


          - name: Deploy package
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.VPS_HOST }}
              port: 22
              username: ${{ secrets.USER_VPS }}
              password: ${{ secrets.USER_PWD }}
              script: |
                mkdir -p /home/tg_bot
                cd /home/tg_bot
                git init
                git pull https://feraclin:${{ secrets.DEPLOY_TOKEN }}@github.com/Feraclin/{{ github.event.repository.name }}.git
                docker-compose down
                docker-compose build
                docker-compose up -d --force-recreate